version: "3"
services:
  app:
    image: lac
    container_name: LAC
    build: ./docker
    ports:
      - 3140:3140
    depends_on:
      - mysql
    privileged: true
    volumes:
      - ./server:/app
    networks:
      - LAC-network
    command:  python3 run.py

  mysql:
    image: mysql
    container_name: LAC-mysql
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "LACkun"
      MYSQL_DATABASE: "LAC"
      MYSQL_PASSWORD: "LACpass"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    restart: 'always'
    expose:
      - 3300
    ports:
      - 3300:3306
    networks:
      - LAC-network
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
networks:
  LAC-network:
    driver: bridge
    name: LAC-network